# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Loanable Equipment and Technology
email: ahummons@depaul.edu
description: > static site mockup
    
baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://ahummons.github.io" # the base hostname & protocol for your site

#sidebar
default-image: owllibrary.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: ahummons

copyright:
   name: 
   link: 

# Build settings
markdown: kramdown
permalink:
paginate: 5
paginate_path: cards/page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus: no

#social
facebook: https://www.facebook.com/dpulibraries
twitter: http://twitter.com/@dpulibrarian
github: http://github.com/ahummons
email: ahummons@depaul.edu

#facebook like box
fb-like-box: yes
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/
fb-page-title: 

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]


theme: jekyll-theme-time-machine
